services:
  db:
    image: postgres:16
    container_name: go_up_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: go_up
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: go_up_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@exemple.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80" 

volumes:
  pgdata:
